check_task/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('files.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

check_task/files/urls.py
from django.urls import path

from . import views

app_name = 'files'

urlpatterns = [
    path('upload_file/', views.UploadFileCreateView.as_view(), name='upload_file'),
    path('files_history/', views.FileHistoryView.as_view(), name='files_history'),
    path('file_detail/<int:file_id>/', views.FileDetailView.as_view(), name='file_detail'),
    path('file_delete/<int:pk>/', views.DeleteFileView.as_view(), name='file_delete'),
    path('file_reload/<int:pk>', views.ReloadFileView.as_view(), name='file_reload'),
]

check_task/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(
        template_name='users/logout.html'), name='logout'),
]

check_task/files/models.py
import os
from django.db import models

from users.models import CustomUser


class StateFile(models.TextChoices):
    """Состояния файла."""
    NEW = 'new'
    RELOAD = 'reload'


class UploadedFile(models.Model):
    """Модель загружаемого файла."""
    user = models.ForeignKey(CustomUser, related_name='files', on_delete=models.CASCADE,
                             blank=True, null=True)
    file = models.FileField(upload_to='uploaded_files/')
    file_state = models.CharField(choices=StateFile.choices, default=StateFile.NEW, max_length=10)
    is_checked = models.BooleanField(default=False)
    notification = models.BooleanField(default=False)
    errors = models.TextField(blank=True, null=True)
    uploaded_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'
        ordering = ('-uploaded_date',)

    def __str__(self):
        return os.path.basename(self.file.name)

check_task/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    email = models.EmailField(_('email'), unique=True)
    username = models.CharField(
        _("username"),
        max_length=150,
        unique=False,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[AbstractUser.username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

check_task/files/forms.py
from django import forms

from files.models import UploadedFile
from users.models import CustomUser


class UploadFileForm(forms.ModelForm):

    class Meta:
        model = UploadedFile
        fields = ('file',)

check_task/users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import CustomUser


class CreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email', )

check_task/files/views.py
import datetime
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.urls import reverse_lazy
from django.shortcuts import redirect, get_object_or_404, render
from django.contrib.auth.mixins import PermissionRequiredMixin

from files.models import UploadedFile, StateFile
from files.forms import UploadFileForm
from services.logic import FileCheck
from services.exceptions import ExtensionError


class UploadFileCreateView(CreateView, FileCheck):
    form_class = UploadFileForm
    template_name = 'files/upload_file.html'
    success_url = reverse_lazy('files:files_history')

    def form_valid(self, form):
        uploaded_file = form.cleaned_data['file']

        try:
            self.check_extension(uploaded_file)
        except ExtensionError as error:
            form.add_error('file', error)
            return self.form_invalid(form)

        form.instance.user = self.request.user
        return super().form_valid(form)


class FileHistoryView(ListView):
    model = UploadedFile
    template_name = 'files/file_history.html'
    context_object_name = 'files'

    def get_queryset(self):
        files = super().get_queryset()
        if self.request.user.is_authenticated:
            return files.filter(user=self.request.user)


class FileDetailView(DetailView):
    model = UploadedFile
    template_name = 'files/file_detail.html'
    context_object_name = 'file'

    def get_object(self, queryset=None):
        file_id = self.kwargs.get('file_id')
        return UploadedFile.objects.get(id=file_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        file = self.get_object()
        if file.errors:
            context['errors'] = eval(file.errors)
        return context


class DeleteFileView(DeleteView):
    model = UploadedFile
    template_name = 'files/delete_file.html'
    success_url = reverse_lazy('files:files_history')
    context_object_name = 'file'


class ReloadFileView(View):
    def get(self, request, pk):
        file = get_object_or_404(UploadedFile, pk=pk, user=request.user)
        form = UploadFileForm(instance=file)
        context = {
            'file': file,
            'form': form,
        }
        return render(request, 'files/reload_file.html', context)

    def post(self, request, pk):
        if UploadedFile.objects.filter(pk=pk).exists():
            file = UploadedFile.objects.get(pk=pk)
            form = UploadFileForm(request.POST, request.FILES, instance=file)

            file_check = FileCheck()

            try:
                file_check.check_extension(request.FILES['file'])
            except ExtensionError as error:
                context = {
                    'file': file,
                    'form': form,
                    'error_message': error,
                }
                return render(request, 'files/reload_file.html', context)

            if form.is_valid():
                form.save()
                file.file_state = StateFile.RELOAD
                file.is_checked = False
                file.notification = False
                file.errors = None
                file.uploaded_date = datetime.datetime.now()
                file.save()
                return redirect('files:files_history')

        return redirect('files:file_detail', pk=pk)

check_task/users/views.py
from django.contrib.auth import login
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('files:files_history')

    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        return response

check_task/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}App title {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>


    <style>
    body {
        background-color: #f0f0f0;
        font-family: "Gill Sans Extrabold", sans-serif;
        font-weight: bold;
    }
  </style>
</head>

<body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer id="myFooter">
      {% include 'includes/footer.html' %}
    </footer>
<script>
    document.getElementById("currentYear").textContent = new Date().getFullYear();
    </script>
<script>
    function adjustFooter() {
        const footer = document.getElementById("myFooter");
        const body = document.body;
        const html = document.documentElement;

        const windowHeight = window.innerHeight;
        const bodyHeight = Math.max(
            body.scrollHeight,
            body.offsetHeight,
            html.clientHeight,
            html.scrollHeight,
            html.offsetHeight
        );

        if (windowHeight >= bodyHeight) {
            footer.style.position = "fixed";
            footer.style.bottom = "0";
            footer.style.left = "0";
            footer.style.width = "100%";
            footer.style.textAlign = "center";
        } else {
            footer.style.position = "static";
        }
    }
    window.addEventListener("load", adjustFooter);
    window.addEventListener("resize", adjustFooter);
</script>
</body>
</html>

check_task/templates/files/delete_file.html
{% extends "base.html" %}

{% block title %}Удалить файл{% endblock title %}

{% block content %}
<div class="container mt-4">
  <h1>Удалить файл "{{ file }}"</h1>
  <div class="module">
    <form action="" method="post">
      {% csrf_token %}
      <p class="lead">Вы уверены, что хотите удалить файл "{{ file }}"?</p>
      <button type="submit" class="btn btn-danger">Удалить</button>
    </form>

    <form action="{% url 'files:files_history' %}" method="get">
      <button type="submit" class="btn btn-secondary">Нет</button>
    </form>
  </div>
</div>
{% endblock %}

check_task/templates/files/file_detail.html
{% extends "base.html" %}

{% block title %}Подробности файла{% endblock title %}

{% block content %}
<div class="container mt-4">
  <p>
    <a href="{% url 'files:files_history' %}" class="btn btn-info">Вернуться к истории файлов</a>
  </p>
  <h1>Подробности файла</h1>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>Имя файла</th>
        <td>{{ file }}</td>
      </tr>
      <tr>
        <th>Состояние файла</th>
          <td>
              {% if file.file_state == "new" %}
                  Новый
              {% elif file.file_state == "reload" %}
                  Перезаписан
              {% else %}
                  {{ file.file_state }}
              {% endif %}
          </td>
      </tr>
      <tr>
        <th>Оповещение</th>
        <td>
            {% if file.notification %}
              <span class="text-success">&#10003; Отправлено</span>
            {% else %}
              <span class="text-danger">&#10007; Не отправлено</span>
            {% endif %}
          </td>
      </tr>
      <tr>
        <th>Дата загрузки</th>
        <td>{{ file.uploaded_date }}</td>
      </tr>
    </tbody>
  </table>

  <div class="text-center">
    <a href="{% url 'files:file_reload' file.pk %}" class="btn btn-primary">Перезаписать</a>
    <a href="{% url 'files:file_delete' file.pk %}" class="btn btn-danger">Удалить</a>
  </div>

{% if file.errors %}
  <div class="alert alert-danger mt-3">
    <h4 class="alert-heading">Ошибки</h4>
    <ul>
      {% for error in errors %}
          <li>{{ error }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

</div>
{% endblock %}

check_task/templates/files/file_history.html
{% extends "base.html" %}

{% block title %}История файлов{% endblock title %}

{% block content %}
<div class="container mt-4">
  <h1>История файлов</h1>
  <table class="table caption-top">
    <thead>
      <tr>
        <th scope="col">№</th>
        <th scope="col">Файл</th>
        <th scope="col">Состояние файла</th>
        <th scope="col">Оповещение</th>
        <th scope="col">Дата загрузки</th>
      </tr>
    </thead>
    <tbody>
      {% for file in files %}
        <tr class="{% if file.errors %}table-danger{% endif %}">
          <th scope="row">{{ forloop.counter }}</th>
          <td>
            <a href="{% url 'files:file_detail' file.pk %}">{{ file }}</a>
          </td>
            <td>
                {% if file.file_state == "new" %}
                    Новый
                {% elif file.file_state == "reload" %}
                    Перезаписан
                {% else %}
                    {{ file.file_state }}
                {% endif %}
            </td>
          <td>
            {% if file.notification %}
              <span class="text-success">&#10003; Отправлено</span>
            {% else %}
              <span class="text-danger">&#10007; Не отправлено</span>
            {% endif %}
          </td>
          <td>{{ file.uploaded_date }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

check_task/templates/files/reload_file.html
{% extends "base.html" %}

{% block title %}Перезаписать файл{% endblock title %}

{% block content %}
<div class="container mt-4">
  <h2>Перезаписать файл "{{ file}}"</h2>

  {% if error_message %}
    <div class="alert alert-danger">{{ error_message }}</div>
  {% endif %}

  <div class="module">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Перезаписать</button>
    </form>
  </div>
</div>
{% endblock %}

check_task/templates/files/upload_file.html
{% extends "base.html" %}

{% block title %}Загрузить файл{% endblock title %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title text-center">Загрузка файла</h2>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              {{ form.label_tag }}
              {{ form }}
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary">Загрузить</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

check_task/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© Copyright <span style="color:#1c8313">Check</span>
    <span id="currentYear"></span></p>
  </footer>

check_task/templates/includes/header.html
<nav class="navbar navbar-light" style="background-color: #0d314e">
  <div class="container">
    <a class="navbar-brand" href="{% if request.user.is_authenticated %}{% url 'files:files_history' %}{% else %}{% url 'users:login' %}{% endif %}">
      <span style="color:#1c8313; font-weight: bold; font-size: 24px;">Check</span>
    </a>
    <ul class="nav nav-pills ml-auto">
      {% with request.resolver_match.view_name as view_name %}
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name == 'files:files_history' %}active{% endif %}" href="{% url 'files:files_history' %}">История</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name == 'files:upload_file' %}active{% endif %}" href="{% url 'files:upload_file' %}">Загрузить файл</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light" href="#" style="color:#ffffff; font-weight: bold; font-size: 15px;">Пользователь: {{ request.user.email }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
      </li>
      {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>

check_task/templates/users/login.html
{% extends "base.html" %}

{% block title %}Войти{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 p-5">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Войти на сайт</h2>
                </div>
                <div class="card-body">
                    {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        {{ error|escape }}
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error|escape }}
                    </div>
                    {% endfor %}
                    {% endif %}
                    <form method="POST" >
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3 p-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        </div>
                        <div class="form-group d-flex justify-content-center align-items-center mt-3">
                            <button type="submit" class="btn btn-primary">Войти</button>
                        </div>
                    </form>
                    <hr>
                    <div class="text-center">
                        Нужен аккаунт? <a href="{% url 'users:signup' %}">Зарегистрироваться</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

check_task/templates/users/logout.html
{% extends "base.html" %}
{% block title %}Вы вышли из системы{% endblock title %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock content %} 

check_task/templates/users/signup.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 p-5">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Регистрация</h2>
                </div>
                <div class="card-body">

                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3 p-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <div class="form-group d-flex justify-content-center align-items-center">
                            <button type="submit" class="btn btn-primary">Зарегистрироваться
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}